### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by ajays97** [context-labs/babyagi-ts#2]
I have set the env variable for `OPENAI_API_KEY` and ran `babyagi run` to assign the _**name**_, _**objective**_, _**initialTask**_ and the llm **__to** the new agent I tried to create. I am getting an error that says
`Request failed with status code 401`

**Comment by samheutmaker** [comment]
Try to export it again or make sure that you have access to the model that you selected upon set up.

**Comment by coyotespike** [comment]
For me this was due to an out of date API key.
